### ISSUE TITLE
KT2021 Death Guard Heavy gunner (and others) not found

### ISSUE THREAD

**Issue by g3rg** [Floppy/dataslate#570]
Death Guard heavy gunner is showing as type='Upgrade' in the battle scribe XML, while the parser is looking for type='Model'. I'm not close enough to know if this is an issue with the BattleScribe data, but I do note that 'DataCard.App' must be using a different selector as it is showing up in that app.

[KT - DeathGuard Testing.ros.txt](https://github.com/Floppy/dataslate/files/7275445/KT.-.DeathGuard.Testing.ros.txt)

**Comment by g3rg** [comment]
List attached should have 5 operatives, only shows the 4. Another Chaos Space Marine list I'm waiting to receive from a friend apparently only shows 2 out of 6 models, will confirm if the same issue when I receive it.

**Comment by Floppy** [comment]
I fixed this in the Battlescribe data just after the initial release, because they should indeed be `Model` instead of `upgrade`, so if you update the data and re-save the roster, it should be fine. I guess DataCard must be using a different selector, yes :)

I've had this reported a couple of times, and if it keeps happening, I'll change the selector, but I'd rather rely on the source data to be accurate if at all possible.
